"""initial schema

Revision ID: c76def170d3a
Revises: 
Create Date: 2026-08-17 14:12:40.949962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c76def170d3a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topics',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('band', sa.Integer(), nullable=False),
    sa.Column('curriculum_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('daily_llm_calls', sa.Integer(), nullable=False),
    sa.Column('daily_window_start', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('auth_sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('user_agent_hash', sa.String(length=64), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('concepts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('topic_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('essential', sa.Boolean(), nullable=False),
    sa.Column('probe', sa.String(length=500), nullable=False),
    sa.Column('aliases_json', sa.JSON(), nullable=False),
    sa.Column('related_json', sa.JSON(), nullable=False),
    sa.Column('curriculum_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('concepts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_concepts_topic_id'), ['topic_id'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_user_id'), ['user_id'], unique=False)

    op.create_table('llm_calls',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_estimate_cents', sa.Float(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_calls_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_calls_user_id'), ['user_id'], unique=False)

    op.create_table('resource_reports',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=128), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resource_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resource_reports_resource_id'), ['resource_id'], unique=False)

    op.create_table('scenarios',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('topic_id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('band', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('prompt_md', sa.Text(), nullable=False),
    sa.Column('artifacts_json', sa.JSON(), nullable=False),
    sa.Column('rubric_json', sa.JSON(), nullable=False),
    sa.Column('target_concepts_json', sa.JSON(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('dedupe_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scenarios_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_scenarios_user_id'), ['user_id'], unique=False)

    op.create_table('attempts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('scenario_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('graded_at', sa.DateTime(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('grade_json', sa.JSON(), nullable=True),
    sa.Column('model_answer_md', sa.Text(), nullable=False),
    sa.Column('disputed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attempts_scenario_id'), ['scenario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attempts_user_id'), ['user_id'], unique=False)

    op.create_table('tutorials',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('concept_id', sa.String(length=64), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body_md', sa.Text(), nullable=False),
    sa.Column('exercise_md', sa.Text(), nullable=False),
    sa.Column('cited_resource_ids_json', sa.JSON(), nullable=False),
    sa.Column('reading_order_json', sa.JSON(), nullable=False),
    sa.Column('related_concept_ids_json', sa.JSON(), nullable=False),
    sa.Column('source_attempt_ids_json', sa.JSON(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('tutorials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tutorials_concept_id'), ['concept_id'], unique=True)

    op.create_table('concept_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('concept_id', sa.String(length=64), nullable=False),
    sa.Column('attempt_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('essential', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('concept_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_concept_events_concept_id'), ['concept_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_concept_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_concept_events_user_id'), ['user_id'], unique=False)

    op.create_table('concept_mastery',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('concept_id', sa.String(length=64), nullable=False),
    sa.Column('misses', sa.Integer(), nullable=False),
    sa.Column('covers', sa.Integer(), nullable=False),
    sa.Column('consecutive_misses', sa.Integer(), nullable=False),
    sa.Column('distinct_miss_scenarios_json', sa.JSON(), nullable=False),
    sa.Column('last_event_at', sa.DateTime(), nullable=False),
    sa.Column('tutorial_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['tutorial_id'], ['tutorials.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'concept_id', name='uq_concept_mastery_user_concept')
    )
    with op.batch_alter_table('concept_mastery', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_concept_mastery_concept_id'), ['concept_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_concept_mastery_user_id'), ['user_id'], unique=False)

    op.create_table('resource_citations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tutorial_id', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=128), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('inline', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tutorial_id'], ['tutorials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resource_citations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resource_citations_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resource_citations_tutorial_id'), ['tutorial_id'], unique=False)

    op.create_table('tutorial_links',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('from_tutorial_id', sa.String(length=32), nullable=False),
    sa.Column('to_concept_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['from_tutorial_id'], ['tutorials.id'], ),
    sa.ForeignKeyConstraint(['to_concept_id'], ['concepts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tutorial_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tutorial_links_from_tutorial_id'), ['from_tutorial_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tutorial_links_to_concept_id'), ['to_concept_id'], unique=False)

    op.create_table('tutorial_reads',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('tutorial_id', sa.String(length=32), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('retested_passed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tutorial_id'], ['tutorials.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tutorial_id', name='uq_tutorial_reads_user_tutorial')
    )
    with op.batch_alter_table('tutorial_reads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tutorial_reads_tutorial_id'), ['tutorial_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tutorial_reads_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutorial_reads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tutorial_reads_user_id'))
        batch_op.drop_index(batch_op.f('ix_tutorial_reads_tutorial_id'))

    op.drop_table('tutorial_reads')
    with op.batch_alter_table('tutorial_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tutorial_links_to_concept_id'))
        batch_op.drop_index(batch_op.f('ix_tutorial_links_from_tutorial_id'))

    op.drop_table('tutorial_links')
    with op.batch_alter_table('resource_citations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resource_citations_tutorial_id'))
        batch_op.drop_index(batch_op.f('ix_resource_citations_resource_id'))

    op.drop_table('resource_citations')
    with op.batch_alter_table('concept_mastery', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_concept_mastery_user_id'))
        batch_op.drop_index(batch_op.f('ix_concept_mastery_concept_id'))

    op.drop_table('concept_mastery')
    with op.batch_alter_table('concept_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_concept_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_concept_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_concept_events_concept_id'))

    op.drop_table('concept_events')
    with op.batch_alter_table('tutorials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tutorials_concept_id'))

    op.drop_table('tutorials')
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attempts_user_id'))
        batch_op.drop_index(batch_op.f('ix_attempts_scenario_id'))

    op.drop_table('attempts')
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scenarios_user_id'))
        batch_op.drop_index(batch_op.f('ix_scenarios_created_at'))

    op.drop_table('scenarios')
    with op.batch_alter_table('resource_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resource_reports_resource_id'))

    op.drop_table('resource_reports')
    with op.batch_alter_table('llm_calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_calls_user_id'))
        batch_op.drop_index(batch_op.f('ix_llm_calls_created_at'))

    op.drop_table('llm_calls')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_user_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_status'))

    op.drop_table('jobs')
    with op.batch_alter_table('concepts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_concepts_topic_id'))

    op.drop_table('concepts')
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_sessions_user_id'))

    op.drop_table('auth_sessions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('topics')
    # ### end Alembic commands ###
