"""conversational training turns

Revision ID: eee4fa16c809
Revises: c76def170d3a
Create Date: 2026-08-18 08:29:58.561178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eee4fa16c809'
down_revision = 'c76def170d3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_turns',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('attempt_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('student_message', sa.Text(), nullable=False),
    sa.Column('assistant_reply_md', sa.Text(), nullable=False),
    sa.Column('follow_up_question', sa.Text(), nullable=False),
    sa.Column('nudge_concept_ids_json', sa.JSON(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'turn_index', name='uq_conversation_turns_attempt_index')
    )
    with op.batch_alter_table('conversation_turns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_turns_attempt_id'), ['attempt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_turns_user_id'), ['user_id'], unique=False)

    # server_default is required on all three, NOT decorative: autogenerate
    # emits these as bare NOT NULL, which fails outright on any database that
    # already has `attempts` rows ("Cannot add a NOT NULL column with default
    # value NULL"). Verified by rolling a database back to the previous
    # revision, inserting an attempt, and upgrading.
    #
    # Pre-existing attempts were graded by the old single-shot flow, so they
    # are already finished: status 'complete', turn_count 1. They have no
    # per-concept coverage record — grade_json already holds their final
    # result, which is what the feedback view and the dispute path read.
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('status', sa.String(length=16), nullable=False, server_default='complete')
        )
        batch_op.add_column(sa.Column('turn_count', sa.Integer(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('coverage_json', sa.JSON(), nullable=False, server_default='{}'))
        batch_op.create_index(batch_op.f('ix_attempts_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attempts_status'))
        batch_op.drop_column('coverage_json')
        batch_op.drop_column('turn_count')
        batch_op.drop_column('status')

    with op.batch_alter_table('conversation_turns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_turns_user_id'))
        batch_op.drop_index(batch_op.f('ix_conversation_turns_attempt_id'))

    op.drop_table('conversation_turns')
    # ### end Alembic commands ###
